name: Test checks
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    container: tokenydev/github-runner:latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@v2'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint sources
        run: npm run lint

      - name: 'Check for uncommitted changes'
        run: |
          git diff --exit-code --stat -- . \
          || (echo "##[error] found changed files after build. please 'npm ci && npm run lint:nofix && npm run test:unit'" \
                   "and check in all changes" \
              && exit 1)

  e2e_test:
    name: E2E tests
    runs-on: ubuntu-latest
    container: node:16
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: 'actions/checkout@v2'

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e
